### PR TITLE
Safely exit if release directory exists on disk

### PR DESCRIPTION
**Pull request by sbesson**
Add a mechanism to exit `prep.sh` if any of the release directories already exists. Goal is to prevent overwriting/double copy of artifacts.

Ideally this exit step should not terminate the release job, allowing improvements of the downloads page using the artifacts in-place.

If for any reason artifacts need to be modified, the release folder would have to be cleaned manually.

### CODE REVIEW

**Comment by sbesson** [comment]
See [OME-merge-release#51](http://hudson.openmicroscopy.org.uk/view/Mgmt/job/OME-merge-release/51/console). After cleaning the `merge-release` directories, `prep.sh` is called twice in a row, the first time to test the artifacts copying/symlinking, the second time to test the exit mechanism.

**Comment by joshmoore** [comment]
An idea (likely for later): what about a flag FAIL_ON_DUPLICATES which is set to true by default. Then if someone knows what they are doing they can set the flag to false in which case a clean exit occurs (as is currently the case with prep.sh)

**Comment by sbesson** [comment]
See [OME-merge-release#53](http://hudson.openmicroscopy.org.uk/job/OME-merge-release/53/console)

**Comment by joshmoore** [comment]
Haven't tested the non-default case, but otherwise looks fine.

**Pull request merged**
