### PR TITLE
Ice35 support for windows

### PR DESCRIPTION
**Pull request by hflynn**
Updating the downloads page for 5.0.x to indicate Ice 3.5 is now supported for Windows

### CODE REVIEW

**Comment by manics** [comment]
Is there a download link for our custom Windows Ice 3.5 builds?

**Comment by hflynn** [comment]
Not yet, @rleigh-dundee is suggesting a separate page for those packages, I need to chat with @sbesson and see if he already had a plan in mind.

**Comment by sbesson** [comment]
No plan in mind although my immediate toughts would be:
- have the Ice 3.5 builds deployed on a separate page as they are independent of a given OME release, e.g. `downloads.openmicroscopy.org/ice/Ice-3.5.1.zip`
- add a reference to this download link in the OMERO downloads page below the server table

**Comment by hflynn** [comment]
I'd second those suggestions - can I leave this open while we prep another page and then add the reference here? Or would a new PR be better?

**Comment by sbesson** [comment]
Handling everything as part of this PR sounds like a good plan.

**Comment by hflynn** [comment]
:+1:

**Comment by hflynn** [comment]
Ready for final review now at http://downloads.openmicroscopy.org/omero/5.0.2-rc2/

**Comment by sbesson** [comment]
Let us review it with final 5.0.2

**Comment by bpindelski** [comment]
All looks good here. Good to merge.

**Comment by hflynn** [comment]
--rebased-to #111

**Pull request merged**
