### PR TITLE
Update mtools downloads icons & text

### PR DESCRIPTION
**Pull request by hflynn**
Ready for the release of mtools 1.2.0 - update to the icons in line with the other pages and also updated text for version compatibility with OMERO.

Still need to know if MCR bundling is changing

### CODE REVIEW

**Comment by jburel** [comment]
Changes look good.

**Comment by hflynn** [comment]
N.B. haven't removed MCR Mac icon image because we still need it for FLIMfit

**Comment by mporter-gre** [comment]
I'm happy with the wording on the download page, the instructions seem quite clear. Thanks Helen!

**Comment by hflynn** [comment]
Done

**Comment by sbesson** [comment]
Deployed as part of OMERO.mtools 1.2.0 release.

**Pull request merged**
