### PR TITLE
FLIMFit downloads page (rebased onto develop)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-58 but rebased onto develop.

---

Add first version of FLIMFit downloads page generation to ome-release.
This PR should be used and tested in coordination with the new http://ci.openmicroscopy.org/view/Consortium/job/FLIMFit-release/ and http://ci.openmicroscopy.org/view/Consortium/job/FLIMFit-release-downloads/ jobs.

/cc @imunro @hflynn

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #58

**Comment by imunro** [comment]
I think we need some text along the lines of " Users who intend to use FLIMfit without OMERO can download either version (for 4.4.x or 5.0.x) as there will be no difference in stand-alone mode."

**Comment by sbesson** [comment]
as in 09af2ac?

**Comment by imunro** [comment]
Ah yes.

**Comment by joshmoore** [comment]
Merging all rebased PRs to ome-release.

**Pull request merged**
