### PR TITLE
Updating copyright years on downloads pages

### PR DESCRIPTION
**Pull request by hflynn**
This was prompted by https://trello.com/c/w1ywT02g/8-downloads-copyright but I figured I may as well update all the pages while I was at it.

Not sure if we want to update all the licenses too, I'm unclear whether we are actually supposed to change CC licenses for existing products, although Jason did ask me to update the schema license to 4.0 so I guess we could.

### CODE REVIEW

**Comment by hflynn** [comment]
N.B. FLIMfit page is updated on #187

**Comment by sbesson** [comment]
Should we try to tokenize this and have the date range replaced as part of the page generation?

**Comment by hflynn** [comment]
That is probably a good idea, do you know how to do it or do I need to investigate?

**Comment by sbesson** [comment]
I think what needs to happen is:
- replace the hardcoded date ranges using a new token e.g. `@DATERANGE@` in all the HTML templates
- have all the Python generating script define the `DATERANGE` key/value pair dyanmically - typically when the substitution dictionary is created https://github.com/openmicroscopy/ome-release/blob/develop/gen.py#L23
- optionally define the default substitution dictionary in https://github.com/openmicroscopy/ome-release/blob/develop/utils.py with the common replacement token (`DATERANGE`, `VERSION`...)

**Comment by hflynn** [comment]
I can add the autoyear generation for the other pages once it's tested for BF.

**Pull request merged**
