### PR TITLE
Improve Bio-Formats downloads page

### PR DESCRIPTION
**Pull request by sbesson**
Fix https://trac.openmicroscopy.org.uk/ome/ticket/11651

This PR redesigns the Bio-Formats downloads page using the same template as the one used for the OMERO download pages. Additionally the Bio-Formats page is divided into four sections (Tools, Components, Code and Legacy).

The descriptions have been copied over from the previous downloads page but some of them may be redundant with the explicit icons.

/cc @melissalinkert, @gusferguson, @hflynn

### CODE REVIEW

**Comment by sbesson** [comment]
Changes built as part of http://hudson.openmicroscopy.org.uk/view/Release/job/BIOFORMATS-4.4-download-page/23/ and deployed onto http://downloads.openmicroscopy.org/bio-formats/4.4.9/index-staging.html for review

**Comment by joshmoore** [comment]
Include tag, SVP?

**Comment by sbesson** [comment]
Done. See  http://hudson.openmicroscopy.org.uk/view/Release/job/BIOFORMATS-4.4-download-page/25/ and deployed onto http://downloads.openmicroscopy.org/bio-formats/4.4.9/index-staging.html.

**Comment by melissalinkert** [comment]
:+1:

**Comment by hflynn** [comment]
Are the two docs links supposed to be pointing at staging?

Other than looks good to me too.

**Comment by sbesson** [comment]
Yes, we used to point at the staging documentation when `STAGING` is turned on. Although I removed this feature from the OMERO downloads page. I can do the same for Bio-Formats so that links point at the final location when reviewing the final page. Thoughts?

**Comment by hflynn** [comment]
I don't see the value of this pointing at staging to be honest. I would just make it point at the final location now.

**Comment by sbesson** [comment]
Done and built in  http://hudson.openmicroscopy.org.uk/view/Release/job/BIOFORMATS-4.4-download-page/26

**Comment by hflynn** [comment]
:+1:

**Comment by sbesson** [comment]
--rebased-to #33

**Pull request merged**
