### PR TITLE
Change legacy to previous versions

### PR DESCRIPTION
**Pull request by hflynn**
The download pages currently use 'legacy' to indicate previous versions - this is both inconsistent with elsewhere on om.org where we use legacy to mean something broader (e.g. covering the OME server), and confusing to users as pointed out by Graeme Ball. This PR changes all the download pages which have these sections to use 'previous versions' instead as this has a clear meaning to users.

To be rebased to dev_4_4 and develop.

### CODE REVIEW

**Comment by hflynn** [comment]
Gah, I missed that mtools also has a 'legacy' section - updating that on https://github.com/openmicroscopy/ome-release/pull/89 to avoid changing the same file on both PRs.

**Comment by sbesson** [comment]
Looks good. Merging (and ready to be rebased on `dev_4_4`/ `develop`

**Comment by hflynn** [comment]
--rebased-to #91

**Comment by sbesson** [comment]
--rebased-to #93

**Pull request merged**
