### PR TITLE
Download page for OME Files C++ 0.1.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sbesson** [comment]
The generated downloads page for OME Files C++ looks very nice @rleigh-dundee . Will have a more thorough review on Monday. One question about the icons.

Someway outside the scope of this particular release, is the choice of using square icons something that should discuss and potentially roll over to all downloads pages across the organization /cc @hflynn @gusferguson @joshmoore @jburel @mtbc

**Comment by ghost** [comment]
@sbesson I asked @gusferguson for the square icons basically because we had already had scaling problems with the number of buttons for the C++ page, and also because the page was getting unreadable.  The icons will allow much easier changes to the page when we change the supported platforms, docs, sources, etc., and also allow for use of a much more compact and easier to read download matrix.

Whether these considerations apply to the other download pages, I'm not sure.  With increased modularity down the line, it might also apply to bioformats and openmicroscopy, so in some ways this is really the first experiment in exposing that level of modularity.

The CSS for the tables is wrong, but I'm no expert and can't figure out how to make sets of two rows alternate for the `split-table` class.  If I remove all the div.xxxtable CSS, it still has a blue background, so I'm not sure I fully follow how the CSS is working here.  That's the remaining cosmetic issue I'm unhappy with.

We're also hitting scaling issues with the amount of hardcoded stuff in the python script as well.  For future releases, we might want to look at how to expose this via the superbuild, since it already has the knowledge of all the packages and versions.  It might make sense to move some of the logic into the superbuild, and have it either create something to be read by the download page script, or maybe even have it generate the full structure directly, since it does everything else already.

**Comment by sbesson** [comment]
All agreed on the extra complexity of the C++ deliverables. Square icons definitely render well to me and we do not have to decide on a rollover policy right now if we are experimenting. We can look at the CSS into more details on Monday.

**Comment by joshmoore** [comment]
Based on the decisions this morning, merging this for 0.1.0. Several things will want looking at, but the primary one (landing page under `/0.1.0/`) is being handled by manually creating files under downloads.o.org.

**Pull request merged**
