### PR TITLE
Update MCR version for FLIMfit

### PR DESCRIPTION
**Pull request by hflynn**
As described above. For 4.8 release.

### CODE REVIEW

**Comment by imunro** [comment]
Looks good to me.

**Comment by sbesson** [comment]
Can you open against `dev_5_0` since we are using this branch historically to release `FLIMfit`. Alternatively, we can switch to `develop` and you can  cherry-pick https://github.com/imunro/ome-release/commit/23d2ba733eb9be605e916bf0121637f27708b529 in this PR.

**Comment by hflynn** [comment]
Ah sorry, I'll just rebase it now.

**Comment by hflynn** [comment]
--rebased-to #142

**Pull request merged**
