### PR TITLE
Remove windows server

### PR DESCRIPTION
**Pull request by hflynn**
Replaces https://github.com/openmicroscopy/ome-release/pull/219 to add guidance for Windows server users and update the download button icon to remove the Windows logo.

### CODE REVIEW

**Comment by hflynn** [comment]
Note that the docs link for windows migration is only on staging just now, the page wasn't merged until after the m9 milestone went live.

**Comment by jburel** [comment]
we can certainly do m10 for Monday to make sure everything is in place since I only noticed it while looking at m9

**Review by mtbc — APPROVED** [review]

**Comment by hflynn** [comment]
http://downloads.openmicroscopy.org/omero/5.3.0-rc1/ looks good

**Comment by hflynn** [comment]
This should be good to merge @jburel

**Pull request merged**
