### PR TITLE
Use new u-track button in u-track downloads page

### PR DESCRIPTION
**Pull request by sbesson**
This PR adds a customized downloads button to the u-track downloads page, courtesy of @gusferguson.

### CODE REVIEW

**Comment by sbesson** [comment]
Built by http://ci.openmicroscopy.org/job/U-TRACK-release-downloads/8/console. See output in http://downloads.openmicroscopy.org/u-track/2.1.1/

**Comment by gusferguson** [comment]
@sbesson - the full-stop on the final bullet point has become detached into a new paragraph. 
" …  main downloads folder

."

**Comment by sbesson** [comment]
Thanks for spotting that. Fixed in http://downloads.openmicroscopy.org/u-track/2.1.1/

**Comment by sbesson** [comment]
--rebased-to #70

**Pull request merged**
