### PR TITLE
Add bio-formats package to the Components table

### PR DESCRIPTION
**Pull request by sbesson**

### CODE REVIEW

**Comment by sbesson** [comment]
Deployed on http://downloads.openmicroscopy.org/bio-formats/5.0.0-rc2/

**Comment by hflynn** [comment]
:+1: from me

**Comment by melissalinkert** [comment]
+1

**Comment by joshmoore** [comment]
Thoughts which may or may not lead @sbesson to modify this PR:
- There's a difference between the 2 doc links: `web documentation` is "latest" while `PDF documentation` is pinned to 5.0.0-rc2.
- Icons for **tools downloads** look great! (Thanks to Gus)
- I'd be slightly :+1: on getting the text beside/below/with each package, but that probably requires a web designer.
- Might be worth mentioning in the text below the **tools downloads** that both bftools.zip and bfmatlab.zip contain bioformats_package.jar
- If we remove the daily/latest split in the updater, we'll likely want to do it for the **components downloads** as well.
- Possibly remove **bioformats_package.jar** from components downloads? The same for **loci_tools.jar**? Somewhere else where all tools jars can live. (No one needs to download each of the components **and** one or more tools jars. In fact, that would be a problem)
- Do we need a zip of all the component jars to simplify this?

**Comment by hflynn** [comment]
Ok, there is no point me fixing up my docs PR until we decide what we are doing with all this, because the docs currently say you have to install the package jar AND the tools, and talk about the daily and latest builds being available...

**Comment by joshmoore** [comment]
Should be good to start reworking this a la openmicroscopy/bioformats#911 now.

**Comment by sbesson** [comment]
Deployed onto http://downloads.openmicroscopy.org/bio-formats/5.0.0-rc3/

**Comment by hflynn** [comment]
Suggestions for bullet points under the main downloads:
- bftools.zip is a bundle of scripts for using Bio-Formats on the command line **now with bioformats_package.jar included so you do not have to install both separately**. See the [command line tools documentation](http://www.openmicroscopy.org/site/support/bio-formats5/users/comlinetools/index.html) for further information. 
- bfmatlab.zip is a bundle of functions for using Bio-Formats from MATLAB. See [Using Bio-Formats in MATLAB](http://www.openmicroscopy.org/site/support/bio-formats5/developers/matlab-dev.html) for more details.

**Comment by sbesson** [comment]
@hflynn: fixed. See http://downloads.openmicroscopy.org/bio-formats/5.0.0-rc3/

**Comment by hflynn** [comment]
:+1: I'm happy with this.
@joshmoore - the difference in the doc links is intentional - this way the pdf links continue to work for old versions while the web docs are over-written by the next release on that branch.
I see the latest/daily split has remained - this is in the docs too, so if we get rid of it, I'll need to update https://github.com/openmicroscopy/bioformats/pull/921 too.

**Comment by joshmoore** [comment]
@hflynn : understood and certainly not a blocker, but it could lead to confusion down the road. i.e. we can postpone the decision, but eventually something like "Current web docs are available at ... A copy of the 5.0.0 docs are also available as PDF"

**Comment by sbesson** [comment]
Makes sense. As the query above  affects both OMERO and Bio-Formats downloads pages, I would rather handle it in a separate PR for either 5.0.0 or 5.0.1.

**Comment by joshmoore** [comment]
No objections.

**Comment by sbesson** [comment]
Built as part of http://downloads.openmicroscopy.org/bio-formats/5.0.0/. Merging.

**Comment by sbesson** [comment]
--rebased-to #57

**Pull request merged**
