### PR TITLE
OMERO 5.2.0-m1

### PR DESCRIPTION
**Pull request by sbesson**
Changes required for building the downloads page of OMERO 5.2.0-m1:
- remove 3.4 artifacts from downloads page
- remove Java variants of OSX Insight

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-release-downloads/4/console and http://downloads.openmicroscopy.org/omero/5.2.0-m1/

**Comment by hflynn** [comment]
Text underneath the clients is going to need updating too, still referencing the Java 6 version

**Comment by hflynn** [comment]
Text under server downloads needs updating to remove references to 3.4 server too

**Comment by sbesson** [comment]
Pushed.

**Comment by hflynn** [comment]
:+1: 
I'd quibble 'servers' in the table but I assume we'll be adding Ice 3.6 servers here at some point so happy to leave it for now.

**Comment by sbesson** [comment]
Agreed, the goal of this PR was mostly to turn the job green and generate a downloads page. If you want, we can start listing all the quibbles/suggestions in a docs card to be addressed in future tags on the OMERO 5.2.0 board.

**Comment by hflynn** [comment]
Hmm, I was going to say a docs card wasn't needed but now I do notice we don't have consistency about plurals in the table headings so I guess that's me starting one.
This should be good to merge though.

**Comment by hflynn** [comment]
https://trello.com/c/P8lzS5xu/78-downloads-page-tidying

**Comment by jburel** [comment]
looking good. Thanks @sbesson

**Pull request merged**
