### PR TITLE
Remove Ice 3.3 server download

### PR DESCRIPTION
**Pull request by ghost**
These look to be the only functional instances of Ice 3.3.  There's also a reference in the "Downloads page generation" part of `README.md`, but I'm not sure if that's outdated.

### CODE REVIEW

**Comment by sbesson** [comment]
--no-rebase `5.1+` only

**Comment by hflynn** [comment]
Can you also delete `/images/ice3_3_download.png` for tidiness sake please?

**Comment by hflynn** [comment]
I'm assuming we are going to handle the Ice 3.5 support for Windows issue on a separate PR.

**Comment by ghost** [comment]
@hflynn Image removed.  Yes, Windows will be separate.

**Comment by hflynn** [comment]
Thanks

**Comment by sbesson** [comment]
See https://downloads.openmicroscopy.org/omero/5.1.0-m0.3/

**Comment by hflynn** [comment]
Looks fine, good to merge.

**Pull request merged**
