### PR TITLE
Fix API weblink & MD5 link on BF downloads page

### PR DESCRIPTION
**Pull request by hflynn**
The API 'read on the web here' link and the MD5 link for the API docs zip downloads aren't working at present on http://downloads.openmicroscopy.org/bio-formats/5.0.1/#api

### CODE REVIEW

**Comment by sbesson** [comment]
To be reviewed as part of 5.0.2-rc1.

**Comment by bpindelski** [comment]
The change looks sensible. There is no http://downloads.openmicroscopy.org/bio-formats/5.0.2-rc2 yet, so couldn't test it live. Should be good to merge nevertheless.

**Comment by bpindelski** [comment]
Correction - there is http://downloads.openmicroscopy.org/bio-formats/5.0.2-rc2/. All looks good there. Links work.

**Comment by hflynn** [comment]
--rebased-to #112

**Pull request merged**
