### PR TITLE
Add support for ice34 builds in gen.py

### PR DESCRIPTION
**Pull request by sbesson**
Since ice33 and ice34 builds can have different numbers, this change allows to pass different build numbers to gen.py to generate the OMERO downloads page.

### CODE REVIEW

**Comment by sbesson** [comment]
See [OME-merge-release#42](http://hudson.openmicroscopy.org.uk/view/Mgmt/job/OME-merge-release/42/)

**Comment by joshmoore** [comment]
For the mock releases this definitely makes sense. For proper releases, however, I'd like to keep the two version numbers in sync via hudson.

**Comment by sbesson** [comment]
I agree. This means we should set up the non-merge release jobs with
`gen.py version b$BUILD_NUMBER`

while the merge release could be using:
`gen.py version b$BUILD_NUMBER b$BUILD__ICE34_NUMBER`

**Comment by joshmoore** [comment]
Makes sense.

**Pull request merged**
