### PR TITLE
Updating Figure downloads page

### PR DESCRIPTION
**Pull request by hflynn**
Figure downloads is still pointing at Will's repo, needed the icon updating as per https://trello.com/c/vPrllKlG/365-new-downloads-buttons, and I also noticed the licensing info & date needed updating in accordance with the changes Jason asked me to make on https://www.openmicroscopy.org/site/about/licensing-attribution

### CODE REVIEW

**Comment by hflynn** [comment]
We might want to replace the announcements URL with http://figure.openmicroscopy.org/#releases too @sbesson ?

**Comment by sbesson** [comment]
If this becomes the reference for announcing releases, works for me.

**Comment by will-moore** [comment]
@hflynn Changes look good, thanks.

**Comment by hflynn** [comment]
I'll merge this since it was used for the release anyway, shall I @sbesson ?

**Comment by sbesson** [comment]
Sounds good

**Pull request merged**
