### PR TITLE
Changes for the 5.0.0-beta2 pages (rebased onto dev_4_4) (rebased onto develop)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-30 but rebased onto develop.

---

This is the same as gh-29 but rebased onto dev_4_4.

---

This PR 
- backports some changes from #12 (in 5.0.0-beta1) tag to handle new 5.0-specific JARs in BF downloads page
- fix non initialized variable when tag is only present on the snoopycrimecop remote
- remove hard-coded versions from `omero_downloads.html`

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #30

**Comment by sbesson** [comment]
This PR contains a series of changes back ported from gh-30 on the 4.4.9 downloads page re Ice 3.5 server.
PR merged in http://hudson.openmicroscopy.org.uk/view/Release/job/OMERO-5.0-download-page/12/console and deployed on http://downloads.openmicroscopy.org/omero/5.0.0-beta2/index.html

**Comment by hflynn** [comment]
Looks good to me. Obviously the Git Tag link will need updating but we knew that anyway.

**Comment by sbesson** [comment]
Yes, the link is currently broken. Since I didn't want to confuse people with a `5.0.0-beta2` version in the merge builds, I removed the 5.0.0-beta2 tags on snoopy after creation. Happy to relaunch the builds with an alternate tag name if necessary.

**Comment by hflynn** [comment]
Nope this is fine for now, makes it nice and clear that it needs updating when the tag version exists.

**Comment by hflynn** [comment]
Good to merge as far as I'm concerned.

**Pull request merged**
