### PR TITLE
updating buttons on OMERO & VA download pages

### PR DESCRIPTION
**Pull request by hflynn**
See https://trello.com/c/vPrllKlG/365-new-downloads-buttons
Updates the OMERO and OMERO Virtual Appliance download pages with new buttons

(I may need to push a second commit to re-use the github buttons on other pages on this branch)

### CODE REVIEW

**Comment by hflynn** [comment]
github_rep_link.png is still used by FLIMfit on this branch, meaning there will be a missing image there now (I actually expected that to make Travis red) but I guess if Travis isn't complaining and we aren't releasing FLIMfit from this branch, it doesn't really matter.

**Comment by hflynn** [comment]
Staged at http://downloads.openmicroscopy.org/omero/5.1.4-rc1/

**Comment by sbesson** [comment]
True. Thanks for remembering :)

**Comment by sbesson** [comment]
Looks good to me.

**Comment by hflynn** [comment]
@pwalczysko you happy too?

**Comment by pwalczysko** [comment]
yes, happy

**Pull request merged**
