### PR TITLE
Refactor prep.sh to allow independent OMERO and Bio-Formats releases  (rebased onto develop)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-21 but rebased onto develop.

---

Test the emptiness of the `OMERO_BUILD` and `BIOFORMATS_BUILD` variables to determine the components to be prepared for release.
For each components, the artifacts checking, the release directory creation and the artifacts symlinking are conditioned by the existence of the corresponding build variable.

### CODE REVIEW

**Comment by joshmoore** [comment]
Does a merge release suffice for testing this?

**Comment by sbesson** [comment]
From gh-21 scenario:

To test this PR, run the merge release job (set up to point at the 5.0.0-beta1 artefacts) with
- [ ] the default parameters
- [ ] an empty OMERO_BUILD variable
- [ ] an empty  BIOFORMATS_BUILD variable
- [ ] empty OMERO_BUILD and BIOFORMATS_BUILD variables

Expecting behaviors are:
- [ ] OMERO and Bio-Formats artifacts are symlinked into a fake snapshots folder and downloads pages are generated  for both
- [ ] artifacts are symlinked and the downloads page is generated for Bio-Formats only
- [ ] artifacts are symlinked and the downloads page is generated for OMERO only
- [ ] job stops early and nothing happens

**Comment by joshmoore** [comment]
`prep.sh` can likely be deleted with the new infrastructure, no?

**Comment by sbesson** [comment]
Correct

**Pull request closed without merging**
