### PR TITLE
Announcement url typo

### PR DESCRIPTION
**Pull request by sbesson**
Reported by @hflynn in #110, this PR should fix the name of the envvar. All the following release jobs have been updated accordingly:
- [X] OMERO-5.0-release
- [X] OMERO-5.0-release-downloads
- [X] WEBTAGGING-release-downloads
- [X] FIGURE-release-downloads

### CODE REVIEW

**Comment by sbesson** [comment]
http://ci.openmicroscopy.org/view/Release/job/WEBTAGGING-release-downloads/13/ definitely went forward with this modification. Thoughts? @hflynn

**Comment by hflynn** [comment]
Looks good to me, want me to merge it?

**Comment by sbesson** [comment]
If you are happy with it, go ahead.

**Comment by hflynn** [comment]
I'll leave you to rebase, thanks.

**Comment by sbesson** [comment]
--rebased-to #115

**Pull request merged**
