### PR TITLE
Modify gen.py to use new tag prefix

### PR DESCRIPTION
**Pull request by sbesson**
This PR should allow the OMERO downloads page to cope with the new tag prefix `v` starting from `5.1.0-m1`

--no-rebase

### CODE REVIEW

**Comment by ghost** [comment]
Looks absolutely fine to me.  Is this tested by any jobs, or just waiting for the milestone release?

**Comment by sbesson** [comment]
To be tested today hopefully by a release job.

**Comment by sbesson** [comment]
See the tag link at https://downloads.openmicroscopy.org/omero/5.1.0-m0.4/#code

**Comment by ghost** [comment]
Looks good to merge if everything is now green.

**Comment by hflynn** [comment]
Looks good to me too, merging.

**Pull request merged**
