### PR TITLE
Add new JAR to Bio-Formats downloads page (rebased onto dev_4_4)

### LINKED ISSUE #37: Add bf doc zip to downloads page
After https://trello.com/c/FBtIp2oT/254-zip-javadoc-for-bf-release it would be nice to have a link to download the docs.

/cc @melissalinkert @sbesson @hflynn

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-47 but rebased onto dev_4_4.

---

This PR:
- adds the new `bioformats_package.jar` to the principal downloads table 
- replaces the Bio-Formats icons used the new ones designed by @gusferguson
- adds the zipped API documentation to the downloads page

Closes #37

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #47

**Comment by hflynn** [comment]
This PR actually adds the BF api docs section to the downloads page in preparation for 4.4.11 and to allow https://github.com/openmicroscopy/ome-release/pull/88 to be rebased onto dev_4_4.

**Comment by sbesson** [comment]
--rebased-from #88

**Comment by joshmoore** [comment]
I assume this needs to go in for the `4.4.11` release?

**Comment by sbesson** [comment]
Absolutely

**Comment by joshmoore** [comment]
I'm inclined to merge then (or to have you do so). If the page isn't what we want, we can always open another PR, and re-run.

**Comment by sbesson** [comment]
Sounds fine. Go ahead.

**Pull request merged**
