### PR TITLE
Add  "use from source" text to FLIMfit downloads page.

### PR DESCRIPTION
**Pull request by imunro**

### CODE REVIEW

**Comment by sbesson** [comment]
Deployed under http://downloads.openmicroscopy.org/flimfit/4.6.4/index-staging.html using the `STAGING` option set to True.

**Comment by hflynn** [comment]
This could do with formatting so that the bullet point lines up with the other ones above. Also Matlab is written as MATLAB above, would be nice to have that consistent. And if you keep the 'use from the Matlab source' bit, I think it would be nice to clarify that you mean the source code on GitHub.

**Comment by hflynn** [comment]
:+1: to wording change & MATLAB. I think the bullet point position should be fixed but we better check a build to confirm.

**Comment by sbesson** [comment]
@imunro: use http://ci.openmicroscopy.org/job/FLIMFit-release-downloads/ to regenerated the page. Do not forget to check the STAGING box to update `index-staging.html` rather than `index.html`.

**Comment by imunro** [comment]
Looks good to me with or without the pedantic full stop.

**Comment by hflynn** [comment]
Merging before anyone else finds some other extreme pedantry to throw at me! For release on the live page tomorrow @sbesson

**Comment by sbesson** [comment]
--rebased-to #83

**Pull request merged**
