### PR TITLE
Searcher downloads page

### PR DESCRIPTION
**Pull request by manics**
The OMERO.searcher downloads page.

### CODE REVIEW

**Comment by manics** [comment]
```
RELEASE=0.1.0-rc1
PYSLIDVERSION=0.1.0
RICERCAVERSION=1.1.3
BUILDNUM=21
```

http://ci.openmicroscopy.org/job/ANALYSIS-OMERO-SEARCHER-release-downloads/5

**Comment by manics** [comment]
Note I'll need some images for the download buttons.

**Comment by pwalczysko** [comment]
@manics I think @gusferguson has some, just contact him please.

**Comment by pwalczysko** [comment]
The situation analogical with the one on `webtagging` (see https://github.com/openmicroscopy/ome-release/pull/65).
The jenkins page shows one artifact, which is `index.html`. When this one is open, we see empty icons which do not link well (except the top one, linking to downloads page).
If this is expected, then this PR works fine.

**Comment by manics** [comment]
@pwalczysko Sorry, the job links were to demonstrate the job was created and run. The final output is at https://downloads.openmicroscopy.org/searcher/0.1.0-rc1/ (and similarly for webtagging).

**Comment by pwalczysko** [comment]
See my comment on the webtagging PR. Is checking the final output enough ? The output for this page seems okay except for the icons, which as I understand you are sorting out in cooperation with @rkferguson.

**Comment by manics** [comment]
@pwalczysko Now updated with the buttons (may need to force the browser to refresh): https://downloads.openmicroscopy.org/searcher/0.1.0-rc1/

Testing: check the page looks correct and works as expected, since this is what users will see if they want to download the software.

**Comment by pwalczysko** [comment]
@manics thank you. Works as expected.

**Comment by manics** [comment]
I've removed the forum post link, it just complicates things.

**Comment by sbesson** [comment]
@manics: want to rebase this onto `develop` (until we sort out the branch where this apps release pages should live) ?

**Comment by manics** [comment]
--rebased-to #75

**Comment by manics** [comment]
@sbesson Done

**Pull request merged**
