### PR TITLE
Add source zip to the source code section in the OMERO downloads page

### PR DESCRIPTION
**Pull request by sbesson**
With https://github.com/openmicroscopy/openmicroscopy/pull/2064, the OMERO source will be generated as a download artifact. This PR adds the zip file to the source code section of the OMERO downloads page.

/cc @rleigh, @gusferguson, @hflynn

### CODE REVIEW

**Comment by sbesson** [comment]
Do we want the file size, name and MD5 as well? In which case, how could we reconcile this with the GitHub hyperlinks?

**Comment by joshmoore** [comment]
I'd say we do want hash and size. What needs to be reconciled?

**Comment by sbesson** [comment]
Minimally the section layout as the existing GitHub icons are just hyperlinks. Do we create 2 tables: one with one row and one with three?

**Comment by sbesson** [comment]
See http://downloads.openmicroscopy.org/omero/5.0.0-rc2/

**Comment by hflynn** [comment]
Source code links look fine.

Forgot to mention this to you the other day but Petr did speak to me about the terminology of build 'artifacts' after speaking to Graeme Ball who said it didn't mean anything to him. Maybe we should change this to 'components' and change the text to 'All the individual components of this release are available here'? Can be a separate PR though, just thought I'd bring it up since I remembered looking at it.

**Comment by sbesson** [comment]
See #48

**Comment by hflynn** [comment]
+1, good to merge from my POV

**Comment by sbesson** [comment]
--rebased-to #49

**Pull request merged**
