### PR TITLE
Final C++ corrections for 5.1.6

### PR DESCRIPTION
**Pull request by ghost**
Correct filenames.

### CODE REVIEW

**Comment by ghost** [comment]
@sbesson Final fix for MacOS X. Now we're just waiting on the CentOS 7 lsb_release installation.

**Comment by ghost** [comment]
Should be final now.  The CentOS7 workaround will need reverting for 5.1.7.

**Comment by hflynn** [comment]
All files download correctly as per https://trello.com/c/v9Y5m1wV/10-downloads-information
Download page looks fine.

**Comment by sbesson** [comment]
02dde53 reverted in #175 for the Bio-Formats C++ 5.1.7 release

**Pull request merged**
