### PR TITLE
Add button to Bio-Formats source code under downloads.oo.org

### PR DESCRIPTION
**Pull request by sbesson**
This PR reuses the source code table from the OMERO downloads page to expose the source code zip produced by the release code in the main downloads page.

/cc @rleigh-dundee

### CODE REVIEW

**Comment by sbesson** [comment]
See http://downloads.openmicroscopy.org/bio-formats/5.0.1-rc1/#code (generated by http://ci.openmicroscopy.org/job/BIOFORMATS-5.0-release-downloads/44/console)

**Comment by hflynn** [comment]
Looks good to me.

**Comment by joshmoore** [comment]
:thumbsup: (@rleigh-dundee thanks you as well!)

**Comment by sbesson** [comment]
--rebased-to #97

**Pull request merged**
