### PR TITLE
Fixes for the 4.4.7 release

### PR DESCRIPTION
**Pull request by sbesson**
Main changes:
- remove trailing and leading comments in the template download pages
- allow annoucement URl to be passed by environment variable

To be tested in the OME-merge-release job

### CODE REVIEW

**Comment by sbesson** [comment]
See [OME-merge-release#50](http://hudson.openmicroscopy.org.uk/view/Mgmt/job/OME-merge-release/50/console) for an application of this PR

**Comment by joshmoore** [comment]
The removal of the "CODE GENERATED" warning is unfortunate, and something we should probably come back to once we migrate plone. Otherwise, this looks fine.

**Comment by sbesson** [comment]
@qidane: any way to insert comments (not rendered in HTML) in the Markdown source of a plone page cf commit 4eb1ac9?

**Comment by joshmoore** [comment]
(Leaving @qidane to comment later) Merging.

**Comment by qidane** [comment]
Not that I could get to work.

**Pull request merged**
