### PR TITLE
Remove daily artifact URLs from the downloads page

### PR DESCRIPTION
**Pull request by sbesson**
Remove the daily artifacts from the downloads page since the BIOFORMATS-5.1-daily job has been deprecated in favor of the BIOFORMATS-5.1-latest job /cc @melissalinkert 
--no-rebase

### CODE REVIEW

**Comment by hflynn** [comment]
Will this be built prior to the m1 release build?

**Comment by sbesson** [comment]
Redeployed at https://downloads.openmicroscopy.org/bio-formats/5.1.0-m1/#components via http://ci.openmicroscopy.org/job/BIOFORMATS-5.1-release-downloads/23/console

**Comment by hflynn** [comment]
Looks fine to me

**Comment by sbesson** [comment]
See https://downloads.openmicroscopy.org/bio-formats/5.1.0-m1/#components

**Pull request merged**
