### PR TITLE
Omero downloads page

### PR DESCRIPTION
**Pull request by sbesson**
This PR uses the HTML template designed by @gusferguson to generate the OMERO downloads page. 
- the Pelican step is skipped for OMERO and no intermediate Markdown file is created
- an additional token is created for the artefact size and logic is added to doc_generator.py to compute human-readable file size
- the images/ folder is copied during `make omero`

/cc @hflynn

### CODE REVIEW

**Comment by sbesson** [comment]
PR merged in the http://hudson.openmicroscopy.org.uk/job/OMERO-stable-download-page/ job

The resulting page is available under
http://downloads.openmicroscopy.org/omero/4.4.9/index-staging.html

**Comment by hflynn** [comment]
As Andrew pointed out, having the checksum link labelled as 'download' is going to confuse our existing users who are used to this indicating the actual software download link.
Let's change this to 'get checksum' as the link text.

**Comment by hflynn** [comment]
:+1:

**Comment by joshmoore** [comment]
- The width on the sizes column is not large enough for values over 100MB (see OMERO.clients-4.4.9-ice35-b98.mac.zip)
- If it doesn't make it too hard to read, I'd make the filenames also a link (modification in place on staging for OMERO.clients-4.4.9-ice35-b98.mac.zip)
- I'd propose `90badbf (MD5)` for the checksum column (modification in place on staging for OMERO.clients-4.4.9-ice35-b98.win.zip)
- It would require one more image, but under "Source code" I'd have a "git tag" element.

**Comment by hflynn** [comment]
Happy with all the updates now.
@joshmoore The filenames as links thing went back to the old idea of having the download links formatted the same as all the other links on the page and rather defeated the purpose of having the new download icons. Gus and I agreed to ditch it when we looked at it.

**Comment by hflynn** [comment]
Will double check all the links later, but happy with the page visually now.

**Comment by hflynn** [comment]
All good except for anchor link which seems to be just my Safari playing up as it works in Chrome and for other people. Good to merge and release AFAIK :+1:

**Comment by hflynn** [comment]
All good!

**Comment by sbesson** [comment]
See http://hudson.openmicroscopy.org.uk/view/Failing/job/OMERO-stable-download-page/67 and the corresponding output http://downloads.openmicroscopy.org/omero/4.4.9/

**Pull request merged**
