### PR TITLE
Changes for the 5.0.0-beta2 pages (rebased onto dev_4_4)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-29 but rebased onto dev_4_4.

---

This PR 
- backports some changes from #12 (in 5.0.0-beta1) tag to handle new 5.0-specific JARs in BF downloads page
- fix non initialized variable when tag is only present on the snoopycrimecop remote
- remove hard-coded versions from `omero_downloads.html`

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #29

**Comment by sbesson** [comment]
NB: most of the commits of #29 were rebased to `dev_4_4` except for the 2 first ones (`develop` JARs specific) and  602003e were the client/server compatibility line remains unchanged on this branch.

**Comment by sbesson** [comment]
This PR has been merged as part of the http://hudson.openmicroscopy.org.uk/view/Release/job/OMERO-4.4-download-page/71/ build. The resulting landing page has been pushed to http://downloads.openmicroscopy.org/omero/4.4.9/index-staging.html for review.

Last commit includes a new icon for the Ice 3.5 server indicating that we do not support it for Windows. What is missing is at least:
- an explanatory line for the Ice 3.5 server drop for Windows
- potentially a link to the relevant forums/email threads
- an announcement on the forum/mailing-lists about why we drop Ice 3.5 for Windows

The three items require a concerted decision at the team level since we are explicitly modifying the scope of our released artifacts /cc @joshmoore, @jburel, @hflynn, @gusferguson, @rleigh-dundee, @jrswedlow

**Comment by hflynn** [comment]
On the actual page, I would add the following under the first server section bullet point:

"If you are using Windows, we recommend you default to using Ice 3.4 and the Ice 3.4 server. The Ice 3.5 server is not supported on Windows because Ice 3.5 requires Python 3, which OMERO does not support (see https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7352 [formatted as proper link obviously]).

**Comment by hflynn** [comment]
With addition to known limitations page, you could change my suggestion to:
"If you are using Windows, we recommend you default to using Ice 3.4 and the Ice 3.4 server. The Ice 3.5 server is not supported on Windows, see [Known Limitations] page for more details."

**Comment by hflynn** [comment]
:+1: build artifacts section

**Comment by hflynn** [comment]
Oh, we've changed to 3.4 clients. Had missed that. Still don't think we need to add client recommendation in the server section though.

**Comment by ghost** [comment]
We do not need to change to 3.4 clients.

**Comment by hflynn** [comment]
Agreed. Can we revert to using 3.5 clients again and remove reference to the client version in this note about the server, please?

**Comment by hflynn** [comment]
New @jrswedlow approved wording (dictated to me)
"If you are using Windows, we recommend you default to using OMERO.server with Ice 3.4. The Ice 3.5 server is not supported on Windows because Ice 3.5 requires Python 3, which OMERO does not yet support (see https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7352 [formatted as proper link obviously])."

And go back to Ice 3.5 clients. Thank you!

**Comment by sbesson** [comment]
Latest changes merged in http://hudson.openmicroscopy.org.uk/view/Release/job/OMERO-4.4-download-page/75/ and rebuilt in http://downloads.openmicroscopy.org/omero/4.4.9/index-staging.html

**Comment by hflynn** [comment]
All good except that do we want to go back to exposing the Ice 3.5 API documentation?
Other than that, server section looks good now.

We need to get those changes to the Known Limitations page merged and released before we release this too though.

**Comment by hflynn** [comment]
Merged docs PR, rebuilding release docs now.

**Comment by sbesson** [comment]
We could also stick to Ice 3.4 for the API documentation since this is the latest Ice version we support for all platforms (and the VM is also built using Ice 3.4).
That being said, this is a really minor point and I am happy to change if people feel 3.5 is more appropriate.

**Comment by hflynn** [comment]
@rleigh-dundee any thoughts re:API docs? Sticking with 3.4 seems the best plan to me on further consideration.

**Comment by ghost** [comment]
Is there any meaningful difference in the API docs between ice34 and ice35?  If not, then why not just go with ice35?

**Comment by joshmoore** [comment]
There are huge differences based on what methods are generated.

**Comment by ghost** [comment]
The methods should all be the same though; our API should be identical and the Ice API is entirely compatible.  Do we have an concrete examples of what's changed?

**Comment by hflynn** [comment]
Ok, let's not get all caught up in this now - how about we add a bullet point note that other versions are available from the build artifacts folder and leave the Ice 3.4 version exposed?

**Comment by hflynn** [comment]
I'm happy with this now. Good to go.

**Comment by sbesson** [comment]
--rebased-to #31

**Pull request merged**
