### PR TITLE
FLIMFit downloads page

### PR DESCRIPTION
**Pull request by sbesson**
Add first version of FLIMFit downloads page generation to ome-release.
This PR should be used and tested in coordination with the new http://ci.openmicroscopy.org/view/Consortium/job/FLIMFit-release/ and http://ci.openmicroscopy.org/view/Consortium/job/FLIMFit-release-downloads/ jobs.

/cc @imunro @hflynn

### CODE REVIEW

**Comment by imunro** [comment]
I think we need some text along the lines of " Users who intend to use FLIMfit without OMERO can download either version (for 4.4.x or 5.0.x) as there will be no difference in stand-alone mode."

**Comment by hflynn** [comment]
General appearance :+1: 
You may want to refer to http://www.openmicroscopy.org/site/products/partner/flimfit/downloads for other text to include.
Also do we want a github link to the code repo?

**Comment by sbesson** [comment]
Done. See http://downloads.openmicroscopy.org/flimfit/4.6.3-staging/

**Comment by hflynn** [comment]
:+1:

**Comment by sbesson** [comment]
--rebased-to #60

**Pull request merged**
