### PR TITLE
Remove the hard-coded version number from the PDF documentation link

### PR DESCRIPTION
**Pull request by sbesson**
Use the `/latest/*manual-pdf` link for the OMERO and Bio-Formats instead. This
allows a patch release such as 4.4.8.1 to keep pointing at the 4.4.8 PDF
documentation (assuming the redirected links are not updated).
Also remove the `PDF_URL` replacement key in gen.py and bfgen.py

### CODE REVIEW

**Comment by sbesson** [comment]
To test this PR, run the [OMERO-merge-release-stable](http://hudson.openmicroscopy.org.uk/view/Mgmt/job/OME-merge-release-stable/) job (with the default parameters). This will copy the 4.4.8 artifacts to a fake snapshots location and generate downloads pages for OMERO and Bio-Formats (as artifacts of the job).

Copy these pages to https://www.openmicroscopy.org/site/products/omero/copy_of_downloads and https://www.openmicroscopy.org/site/products/bio-formats/copy_of_downloads.

The look at the resulting page and check the link are valid, especially the ones for the PDF documentation.

**Comment by hflynn** [comment]
Both pages look fine and the pdf and doc links work, good to merge.

**Comment by joshmoore** [comment]
If we maintain old download pages though, this will no longer hold true, right? For a patch release it makes perfect since, but it may work against us for proper releases. Likely we will need to split logic further between the two types. TBD with @sbesson on return.

**Comment by hflynn** [comment]
I realise the old download pages continue to exist as artifacts of the job for as long as the build is kept on jenkins, but we don't actually link to them anywhere - is there any particular reason we need to maintain the pdf links in them?

**Comment by joshmoore** [comment]
I think we would need to keep the download pages in the directories along with the artifacts in order to have a sensible index for each version.

**Pull request merged**
