### PR TITLE
5.1.0 rc1

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/xEcNAqQq/237-bio-formats-c

Changes in preparation of 5.1.0-rc1:
- refactors utility functions `get_version`, `get_tag` to a single `utils.py`
- define constants inside `utils.py` and change the default root for downloads static content
- split Bio-Formats downloads pages into two: Java and C++

/cc @rleigh-dundee @hflynn 

--no-rebase

### CODE REVIEW

**Comment by ghost** [comment]
Is it possible to view the generated pages?

**Comment by sbesson** [comment]
I need to go through the release process which I'll do today and paste links here.

**Comment by sbesson** [comment]
Current version deployed at https://downloads.openmicroscopy.org/bio-formats-cpp/5.1.0-m5/. Next to do items in terms of this PR:
- [ ] add explanatory lines for supported/unsupported versions  /cc @hflynn 
- [ ] add Ubuntu 14.0.4 plaftorm (likely under supported versions)
- [ ] decide if all OS X platforms should be exposed 
- [ ] fix icons for new platforms /cc @gusferguson

While the 14.04 item also requires some CI work (enabling in the matrix), feel free to open PRs against my branch.

**Comment by gusferguson** [comment]
@sbesson - I need specific requirements for the icons in terms of:
- what page they will be going on
- download format e.g. zip, jar
- associated icon e.g. Windows, Mac, Linux, etc.
- exact text
  Thanks.

**Comment by sbesson** [comment]
@gusferguson: minimally:
- the icons will be all be exposed on the page linked above (i.e. the new Bio-Formats C++ landing page)
- the download format will likely be of form `.tar.xz` for non Windows platforms and `zip` for Windows
- we may want icons matching the supported/unsupported platforms. At the moment we have CentOS and OS X icons but are hoping to get an Ubuntu build soon
- I would be inclined to unify the text to be of the form `PLATFORM VERSION C++ binaries`.

The full list of `PLATFORM VERSION` still depends on upstream decisions /cc @joshmoore @rleigh-dundee

**Comment by joshmoore** [comment]
Comments/questions:
- I'd go all the way to the bottom for unsupported versions. (or only in artifacts?)
- Artifacts at the bottom isn't yet working.
- Should full documents go to the C++ landing page? (separate PDF?)

Otherwise, :+1:

**Comment by gusferguson** [comment]
@sbesson - I will do an example icon and everyone can feedback on that - then once the text is finally determined it will just take minutes to generate as many variations as needed. Hopefully be able to do it later today.

**Comment by hflynn** [comment]
I wouldn't put the unsupported versions below 'Previous versions' but you could move them below the code. I'll open a PR against this to amend the doc links at the top and add supported vs unsupported explanatory text.

**Comment by gusferguson** [comment]
I seem to be well set up already for these buttons - I had forgotten I had done more than I needed to last time. So all I really need is a list giving the **exact** text for the new buttons.

Eg of Windows and FreeBSD versions

bf_c _win_8_2

bf_c _freebsd_10_1_2

**Comment by sbesson** [comment]
Re the unsupported versions, I am debating fully removing this table and have a simple sentence with a link to artifacts instead. As we do not officially support them, the table has little value. This would also greatly simplify the icon work. Thoughts?

**Comment by gusferguson** [comment]
@sbesson  - sounds good to me!

**Comment by sbesson** [comment]
@gusferguson: the changes above involve that the only icon we really need for now should have:
- a `tar.xz`  download format 
- a Bio-Formats/Ubuntu icon
- `Ubuntu 14.04 C++ binaries` as the text

**Comment by gusferguson** [comment]
@sbesson - OK will do it now - do you want it emailed to you or should I just put it in a comment here?

**Comment by sbesson** [comment]
A comment on this PR should work fine.

**Comment by gusferguson** [comment]
@sbesson 

bf_c _ubuntu_14_04

**Comment by sbesson** [comment]
Last commit was built and is available at https://downloads.openmicroscopy.org/bio-formats-cpp/5.1.0-m5/ for review. Any blocker/critical fix to bring as part of this PR? Else I propose we get this merged and carry out improvements in separate PRs.

**Comment by joshmoore** [comment]
Not a blocker. I would suggest either per-OS subdirectories or some order to http://downloads.openmicroscopy.org/bio-formats-cpp/5.1.0-m5/artifacts/ (we don't have to make it easy, but we don't have to obfuscate it either).

**Comment by sbesson** [comment]
Thanks all.
On the artifacts discussion, I will fix things to not copy the zips and may simply drop the .md5 checksums in favor of sha1 only which should greatly reduce the artifacts list. If we want to organize artifacts in sub-folders, please say so in the Trello card (should the apidocs be copied per platform in this case?).
Merging this for code freeze.

**Comment by ghost** [comment]
@sbesson Have you considered putting all the sha1sums into a single file? i.e.

```
rm -f sha1sums
find -s * -type f -depth 1 -print0 | xargs -0 sha1sum > sha1sums
```

Similar could be done for md5sums.  This makes the directory listing cleaner.  And you can PGP sign the file (detatched or inline) to allow easy verification of the entire set of files in one go.

**Comment by sbesson** [comment]
@rleigh-dundee: re-thinking about it, the only downside of a single sha1sum file (although I like the idea) is that the downloads table are currently linking to the sha1 file for each artifact. Changing this to have a single file instead would imply a major refactoring of all downloads page (for consistency). Moving to a card for discussion.

**Comment by joshmoore** [comment]
Both?

**Pull request merged**
