### PR TITLE
bfcpp: Add unsupported downloads

### PR DESCRIPTION
**Pull request by ghost**
- Correct top links
- Change "platform" to "build"; there's a big difference between a _platform_ being unsupported and a _specific build_ for a platform being unsupported (we will support Mac and CentOS even though we can't directly support our downloadable build)
- Add "Unsupported builds" section.  Discussed with Petr; the lack of these builds on this page makes them completely invisible to the end user who wants to download it, and it makes it look like these platforms are entirely unsupported.  The caveats are noted at the end of the section.

### CODE REVIEW

**Comment by hflynn** [comment]
I was just suggesting on the card that maybe just listing the available platforms in the text for the unsupported section was the best compromise, that at least removes the need to keep updating icons etc, but up to you.

**Comment by ghost** [comment]
@gusferguson Would it be possible to have download buttons for MacOS X 10.10 and FreeBSD to match the existing Ubuntu 14.04 one?  The existing MacOS 10.9 and CentOS 6.5 ones might possibly need updating if the Ubuntu one is the only one which is up-to-date.  Thanks!

To distinguish debug and release, separate buttons would also be useful.  Maybe a "bug" of some sort on the debug one?

**Comment by ghost** [comment]
@hflynn I don't think the icons should need updating _that_ frequently; the version numbers may need updating when new OS releases come out, but that's not particularly frequent--we shouldn't need to do this e.g. every Bio-Formats point release.

If we decide to make the icons into SVG files at some point, it would then make updating the text in them trivial.

**Comment by hflynn** [comment]
Fair enough.

**Comment by sbesson** [comment]
No veto from my side. Note the unsupported section had been discussed - see https://github.com/openmicroscopy/ome-release/pull/139#issuecomment-77370886 and this effectively revert the modifications of this PR. Once we get this page built and reviewed via the 5.1.0-m5 build tomorrow, I suggest we reach a final agreement across the board on the layout of this downloads page and freeze it for 5.1.x. /cc @joshmoore @gusferguson @melissalinkert @pwalczysko

**Comment by gusferguson** [comment]
@rleigh-dundee @hflynn @sbesson - I will do the buttons ASAP today.

**Comment by ghost** [comment]
@sbesson Do you want a chat about this today?

**Comment by gusferguson** [comment]
@rleigh-dundee @hflynn @sbesson 

How are these?

bf_c _ubuntu_14_04_txz

bf_c _ubuntu_14_04_txz_debug

bf_c _freebsd_10_1_txz

bf_c _freebsd_10_1_txz_debug

bf_c _mac_10_10_txz

bf_c _mac_10_10_txz_debug

bf_c _api_docs_txz

**Comment by gusferguson** [comment]
@rleigh-dundee @hflynn @sbesson 

Although strictly speaking we should update the Mac icon to the Yosemite "flat" version. Use these if you don't mind being slightly ahead of the other Mac download buttons:

bf_c _mac_10_10_txz_yos

bf_c _mac_10_10_txz_debug_yos

**Comment by ghost** [comment]
@gusferguson They look great, thanks.  I do like the sniper scope on the bug!  (Thought ladybirds were "nice" bugs though!)

**Comment by gusferguson** [comment]
@rleigh-dundee - I wracked by brains for a vegan version but failed! :-)

**Comment by ghost** [comment]
@gusferguson If we could possibly have MacOS X 10.9 and CentOS 6.5 versions to complete the set, that would be great!

**Comment by gusferguson** [comment]
@rleigh-dundee @hflynn @sbesson 

bf_c _centros_6_5_txz_debug

bf_c _centros_6_5_txz

bf_c _mac_10_9_txz_debug

bf_c _mac_10_9_txz

**Comment by ghost** [comment]
@gusferguson Thanks, I've added these now.

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-release-cpp-downloads/16/console. 10.9 artifacts are neither produced by the latest nor the release cpp builds at the moment. Should we extend the matrix to do so?

**Comment by ghost** [comment]
@sbesson Yes, please.  Having 10.9 now we've dropped 10.8 would be great.

**Comment by ghost** [comment]
Just as a general comment, it would be good to come up with a better descriptive text than "supported" or "unsupported" since the distinction is not at all clear.  We do support all the platforms here, but the builds for some platforms may stop working when the platform is updated.  I don't know if there's a better way of wording things, but if anyone has any thoughts?

**Comment by gusferguson** [comment]
"Active development" "Not currently being developed" ?

**Comment by ghost** [comment]
@gusferguson That distinction is definitely in the right direction, but the wording isn't quite right.

**Comment by hflynn** [comment]
What about something along the lines of 'robust' and 'fragile'?

**Comment by gusferguson** [comment]
@rleigh-dundee @sbesson 

bf_c _centros_6_6_txz_debug

bf_c _centros_6_6_txz

bf_c _centros_6_txz_debug

bf_c _centros_6_txz

bf_c _centros_7_txz_debug

bf_c _centros_7_txz

**Comment by ghost** [comment]
@gusferguson Many thanks, they all look great.  I've added these in the above commits.

**Comment by hflynn** [comment]
This is really getting rather wordy now. I'll have a think tomorrow morning but I think we probably need to rephrase the text a bit.

**Comment by sbesson** [comment]
See https://downloads.openmicroscopy.org/bio-formats-cpp/5.1.0-m5/#unsupported for the current version of this PR

**Comment by ghost** [comment]
@sbesson Thanks, looks OK.  Looks technically correct, though @hflynn might want to reword things.  From the presentation side, it would be nice if the Filename column could be increased in width to improve the legibility of the text, but my HTML-fu is quite limited--we could increase the size easily enough, but could this be made more dynamic rather than hardcoding fixed pixel sizes?

**Comment by hflynn** [comment]
Ok, looking at the current built page:
- Let's take the developer preview warning off to the very top now ready for the release
- 1st bullet point in the 'unsupported' section, let's rephrase to
  "Unsupported builds are available for rolling-release platforms (BSD ports, MacOS X homebrew). As the packages and libraries provided by the rolling release (and required by Bio-Formats) may be updated incompatibly, we cannot guarantee these specific binary builds will be usable in the future."
- 3rd bullet point in the unsupported section - let's make the requirements covered in the documentation a link to http://www.openmicroscopy.org/site/support/bio-formats5.1/developers/cpp/overview.html

Otherwise, I think we are sorted now.

**Comment by ghost** [comment]
@hflynn Done.  Note the cpp/overview.html link will be invalid until the docs are regenerated.

**Comment by joshmoore** [comment]
Looks like the links at the top are missing a separator: `CodePrevious versions`

**Comment by hflynn** [comment]
Oh yeah, @joshmoore is right - the entire block is linking to the code section, that'll need fixed.

**Comment by ghost** [comment]
@hflynn Separator added; the links look OK though.

**Comment by hflynn** [comment]
So it does, should be fine now

**Comment by sbesson** [comment]
Merging post 5.1.0-m5 acceptance. Thanks all.

**Pull request merged**
