### PR TITLE
Add logic to symlink promoted virtualbox artifacts

### PR DESCRIPTION
**Pull request by sbesson**
To test this PR:
- promote OMERO-stable, OMERO-stable-ice34 and OMERO-stable-virtualbox jobs
- run OME-merge-release-stable and check the virtualbox artifacts have been properly symlinked

### CODE REVIEW

**Comment by joshmoore** [comment]
It should be possible to test this with either a develop `alpha5` or a 4.4.9 `rc1` right?

**Comment by sbesson** [comment]
correct. Now the virtualbox target has been changed and the virtualbox use promotion, this should be testable for our next RC/alpha.

**Comment by sbesson** [comment]
NB: I can open a staging ome-internal doc PR to describe the updated release process maybe?

**Comment by joshmoore** [comment]
Still planning on testing with the next alpha tag.

**Pull request closed without merging**
