### PR TITLE
Flimfit 4.10

### PR DESCRIPTION
**Pull request by sbesson**
Modifies FLIMfit downloads page for the 4.10.3 release /cc @imunro

### CODE REVIEW

**Comment by imunro** [comment]
MCR links need updating to 2015b (v9.0)

**Comment by imunro** [comment]
Same issue (MCR version no) in body of text under Mac Users

**Comment by imunro** [comment]
On my mac I am unable to open the .zip file downloaded from http://downloads.openmicroscopy.org/flimfit/4.10.3/
The unzipped file obtained from http://ci.flimfit.org/job/flimfit-release-mac/gcsObjects/ Is fine. N.B> I am clicking on the "Downloads" link.

**Comment by imunro** [comment]
Similar issue with the artefacts on Windows. Unzips but resulting file won't run.

**Comment by imunro** [comment]
Just retested on Windows following changes - thanks @sbesson . Download now unzips, installs and passes minimal testing. Only  issue is that after unzipping I see a "MACOSX" subdir - see screenshot.
screen shot 2016-02-17 at 15 00 40

**Comment by imunro** [comment]
Retested on the mac and all seems well now. Runs and passes minimal testing.

**Comment by imunro** [comment]
MCR version Nos now updated by https://github.com/openmicroscopy/ome-release/pull/184  Which, I guess, supercedes this PR.

**Comment by sbesson** [comment]
Thanks @imunro closing this PR.

**Comment by imunro** [comment]
NP To my surprise I managed not to break anything :-)

**Pull request closed without merging**
