### PR TITLE
Update FLIMfit downloads page for 4.6.6 release

### PR DESCRIPTION
**Pull request by sbesson**
- Restore Windows downloads and remove 4.6.4-specific line 
- Add MCR downloads table and fix MCR sentence

/cc @imunro @hflynn

### CODE REVIEW

**Comment by sbesson** [comment]
See http://downloads.openmicroscopy.org/flimfit/4.6.6/

**Comment by hflynn** [comment]
All looks good to me :+1:

**Comment by sbesson** [comment]
Merging after 4.6.6 release testing.

**Comment by sbesson** [comment]
--rebased-to #99

**Pull request merged**
