### PR TITLE
Changes for the 5.0.0-beta2 pages

### PR DESCRIPTION
**Pull request by sbesson**
This PR 
- backports some changes from #12 (in 5.0.0-beta1) tag to handle new 5.0-specific JARs in BF downloads page
- fix non initialized variable when tag is only present on the snoopycrimecop remote
- remove hard-coded versions from `omero_downloads.html`

### CODE REVIEW

**Comment by sbesson** [comment]
See [OMERO-5.0-download-page#6](http://hudson.openmicroscopy.org.uk/view/Release/job/OMERO-5.0-download-page/6/console) and [BIOFORMATS-5.0-download-page#3](http://hudson.openmicroscopy.org.uk/view/Release/job/BIOFORMATS-5.0-download-page/3/console)

**Comment by hflynn** [comment]
OMERO page:
- The 'web documentation' link in the first section is pointing at OMERO 4 docs, as are the OMERO client doc links under the client downloads table 
- The last bullet point under the clients section needs to link to 'Getting Started with OMERO.insight Version 5.0 beta' at http://help.staging.openmicroscopy.org/getting-started-5.html
- Matlab doc link under plugins is also pointing at OMERO 4 docs
- Server installation doc links are all pointing at OMERO 4 docs
- VA doc link is pointing at OMERO 4 too
- So is the 'installing OMERO from source' doc link at the bottom of the page

Other than those issues, looks good!

**Comment by sbesson** [comment]
@hflynn: thanks for these points, I will modify them accordingly and regenerate the pages. 

Regarding the second byllet point , can I enquire what the strategy is on the help front. The links on the 4.4.9 use an explicit release version  `Getting Started with OMERO.insight Version 4.4.9`. On the other hand, `Getting Started with OMERO.insight Version 5.0 beta` lacks specificity especially if we are release several betas and a `5.0` release. What are your thoughts?

**Comment by hflynn** [comment]
BF page:
- Links all look fine except that the ImageJ 'user guide' doc link appears to have https hard-coded.
- Can you remove the word 'page' after the 'online documentation' link just above the trunk/daily builds section, please.

Other than that, I'm wondering if we can do a bit of a make-over on the top of the page to match the new OMERO one. I think the table of components is fine for developers, but maybe we could have the LOCI tools, bftools and Matlab Toolbox formatted with logo buttons under the heading 'Bio-Formats Bundles' at the top? I could ask Gus to mock something up?

**Comment by hflynn** [comment]
Re: Help pages. Hmmm, yeah, actually I guess we will need to change that to 5.0.0-beta2 for the next release, aren't we? Ok, have the link as getting-started-5.html but format the link text as 'Getting Started with OMERO.insight Version 5.0.0-beta2 and I'll get Gus to update the title for the release.

**Comment by hflynn** [comment]
Right, Gus is going to make icon buttons for LOCI tools, Command line tools and the MATLAB Toolbox this am.

**Comment by sbesson** [comment]
@hflynn: all comments should have been addressed and the downloads page regenerated. See
http://downloads.openmicroscopy.org/omero/5.0.0-beta2/ and  http://downloads.openmicroscopy.org/bio-formats/5.0.0-beta2/

**Comment by hflynn** [comment]
'Getting Started with OMERO.insight Version 5.0.0-beta2 is still pointing at http://help.openmicroscopy.org/getting-started-4.html rather than -5.html

Other than that, all looks sorted now :+1:

**Comment by sbesson** [comment]
Last commit should fix the help URL see regenerated downloads page

**Comment by hflynn** [comment]
Great. Good to merge as soon as @melissalinkert has confirmed she is ok with the Bio-Formats page (the further changes happening on another PR later).

**Comment by melissalinkert** [comment]
All seems fine to me.

**Comment by sbesson** [comment]
--rebased-to #30

**Pull request merged**
