### PR TITLE
First version of figure downloads

### PR DESCRIPTION
**Pull request by sbesson**
/cc @will-moore

### CODE REVIEW

**Comment by sbesson** [comment]
Deployed by http://ci.openmicroscopy.org/view/Consortium/job/FIGURE-release-downloads/3/ on http://downloads.openmicroscopy.org/figure/1.0.0-beta1/.

**Comment by will-moore** [comment]
Looks good - All links seem to be fine etc.

**Comment by sbesson** [comment]
Great. Merging for tomorrow's release. Future improvements to the page will be done by PR as usual.

**Comment by sbesson** [comment]
--rebased-to #80

**Pull request merged**
