### PR TITLE
Webtagging downloads page

### PR DESCRIPTION
**Pull request by sbesson**
First version of the webtagging downloads page generation

/cc @dpwrussell

### CODE REVIEW

**Comment by sbesson** [comment]
http://ci.openmicroscopy.org/view/Release/job/WEBTAGGING-release-downloads/12/

**Comment by pwalczysko** [comment]
In the highlighted jenkins page, there is an `index.html` built (as the only file). When `index.html` is opened, it shows something like a skeleton of a downloads page, although with no icons and the links do not work, except the top one, which links to downloads page. See screenshots. If this is expected, than the PR is fine.

The other screenshot

screen shot 2014-03-10 at 09 51 31

**Comment by pwalczysko** [comment]
screen shot 2014-03-10 at 09 48 48

**Comment by dpwrussell** [comment]
I think @sbesson will have to answer this, but I assume it has something to do with him customising it for webtagging with the final host location in mind. The page generated by this and symlinked correctly displays: http://downloads.openmicroscopy.org/webtagging/1.0.0/

**Comment by sbesson** [comment]
Sorry for the misunderstanding. Yes the output of this PR is deployed on the link pasted above by Douglas.

**Comment by pwalczysko** [comment]
Yes, the url pasted by @dpwrussell shows a page which is correctly symlinked and has icons. Not sure still though what is to be tested here - is that all what is asked (to check the page) ? What is the scope of this PR and how to test it ?

**Comment by sbesson** [comment]
@pwalczysko: yes all this PR is doing is creating the downloads page from a template. Note this has impact on how we may review partner projects in the future as we may want to apply the same strategy as core OME products, i.e. create RCs, prepare LDAP-protected downloads pages and review from there instead of using the CI builds.

**Comment by pwalczysko** [comment]
Okay, understood, thanks. All fine here then.

**Comment by sbesson** [comment]
--rebased-to #69

**Pull request merged**
