### PR TITLE
Validate and tidy html files

### PR DESCRIPTION
**Pull request by qidane**
I cleaned up the files, fixed validation errors and formatted them.

They need tested, there were some invalid tokens I have commented out, but they might have been important to some build system as markers.

Need checked by @sbesson and @hflynn

Oh, and why are there two `flimfit_downloads.html`?

### CODE REVIEW

**Comment by hflynn** [comment]
@sbesson can we test-build these today to check or do we need to wait for 5.0.1-rc1? Or is there a way to build locally for testing?

**Comment by sbesson** [comment]
I could create a staging page I guess. But 5.0.1-rc1 would be cleaner.

**Comment by hflynn** [comment]
Fine, will review this when that is ready then.
Thanks @qidane

**Comment by sbesson** [comment]
@qidane: general questions:
- what is your validation tool?
- is there a way to auto-validate in the Travis build?
- what sets the character limit per line?
- why are the tab 7 characters?

**Comment by qidane** [comment]
I did the layout and validation using Oxygen, I think it used something like `tidy` behind the scenes and it was validated using the `xerces` library. All my xml files are formatted using tabs, but I usually view them as 4 characters wide, if they are 7 wide it must be the way the editor you are using is displaying them. Wrap limit is set in Oxygen, the default value seems to be 100 for xhtml files.

**Comment by hflynn** [comment]
I think this is better thanks. What do you think @sbesson - are you happier with this narrower layout? Or is it too narrow now?
Just waiting on the test build to check if the 'invalid' stuff is actually needed from my POV.

**Comment by sbesson** [comment]
Looks great @qidane. I like this layout as it simplifies diffs visualization using GitHub but this is a style discussion.
Ready for review by @hflynn.

**Comment by qidane** [comment]
Waiting for RC downloads page before review

**Comment by sbesson** [comment]
Deployed on http://downloads.openmicroscopy.org/omero/5.0.1-rc1/ via http://ci.openmicroscopy.org/job/OMERO-5.0-release-downloads/34

**Comment by sbesson** [comment]
Deployed on http://downloads.openmicroscopy.org/bio-formats/5.0.1-rc1/ via http://ci.openmicroscopy.org/job/BIOFORMATS-5.0-release-downloads/42

**Comment by hflynn** [comment]
The only issue I'm seeing is that we have lost any spacing for the left-hand margin - all the text starts right up against the edge of the page. Other than that, all the formatting looks fine and the navigation links work etc.

**Comment by hflynn** [comment]
@sbesson Apparently the spacing issue is a quick fix. Andrew will do it first thing tomorrow if he doesn't have chance this evening.

**Comment by qidane** [comment]
Fixed OMERO and Bio-Formats, will sort others later.

**Comment by hflynn** [comment]
Thanks!

**Comment by sbesson** [comment]
OMERO and Bio-Formats 5.0.1-rc1 pages re-deployed

**Comment by hflynn** [comment]
BF & OMERO pages definitely fine now. Do we want to rebuild the partner project pages to check them before merging though?

**Comment by sbesson** [comment]
Either we could do that now or as part of the next release cycle for each of them. Consensus proposal: pick a couple of them and try it out (as I need to change permissions and generate staging pages).

**Comment by sbesson** [comment]
See for instance http://downloads.openmicroscopy.org/flimfit/4.6.4/index-staging.html vs http://downloads.openmicroscopy.org/flimfit/4.6.4/index.html

**Comment by hflynn** [comment]
Aside from the update I made (legacy -> previous), the only difference is that the page now has 'FLIMfit' across the top of my browser window rather than the full url. Which is a good change to my mind.
Good to merge I think.

**Comment by sbesson** [comment]
@qidane: any additional change planned?

**Comment by qidane** [comment]
nope

**Comment by sbesson** [comment]
Thanks. Merging for 5.0.1-rc1. Can you rebase onto `develop`?

**Comment by hflynn** [comment]
--rebased-to #95

**Pull request merged**
