### PR TITLE
Update MCR links to 2014b (rebased onto develop)

### PR DESCRIPTION
**Pull request by hflynn**
This is the same as gh-140 but rebased onto develop.

---

### CODE REVIEW

**Comment by hflynn** [comment]
--rebased-from #140

**Comment by hflynn** [comment]
Rebased for completeness so we can release from the develop branch in future if needed and the two are in sync.

**Comment by hflynn** [comment]
@sbesson I assume your extra commit is ok here?

**Comment by sbesson** [comment]
It certainly does not hurt.

**Pull request merged**
