### PR TITLE
Ice35 support for windows (rebased onto develop)

### PR DESCRIPTION
**Pull request by hflynn**
This is the same as gh-106 but rebased onto develop.

---

Updating the downloads page for 5.0.x to indicate Ice 3.5 is now supported for Windows

### CODE REVIEW

**Comment by hflynn** [comment]
--rebased-from #106

**Comment by sbesson** [comment]
Looks good. Since this is not a straight rebase, a minor point, we are adding an Ice 3.3 icon which is deprecated on this branch. Worth removing?

**Comment by hflynn** [comment]
Ah, I missed that. I'll delete it.

**Comment by hflynn** [comment]
Done

**Comment by sbesson** [comment]
Thanks. Merging.

**Pull request merged**
