### PR TITLE
OMERO.py downloads

### PR DESCRIPTION
**Pull request by joshmoore**
There have been various requests for a Python bundle (e.g. https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=7516&p=13982). Though this isn't yet pip-installable, having the download clearly marked on the downloads page is a start. **Note:** the download is available for previous versions as well, though it's likely not worth changing previous download pages:

```
 /ome/data_repo/public/omero $ ls -1 5.0.*/artifacts/OMERO.py*ice33*zip
5.0.0-rc1/artifacts/OMERO.py-5.0.0-rc1-ice33-b10.zip
5.0.0-rc2/artifacts/OMERO.py-5.0.0-rc2-ice33-b14.zip
5.0.0/artifacts/OMERO.py-5.0.0-ice33-b19.zip
5.0.1/artifacts/OMERO.py-5.0.1-ice33-b21.zip
5.0.2-rc1/artifacts/OMERO.py-5.0.2-rc1-ice33-b22.zip
```

/cc @sbesson @ximenesuk @hflynn @pwalczysko @manics @chris-allan

Keep in mind that the importer is not included, but the following works: `/tmp/OMERO.py-5.0.2-rc1-ice35-b22$ bin/omero import -s root@gretzky.openmicroscopy.org.uk --clientdir=/opt/ome2/dist/lib/client/`

### CODE REVIEW

**Comment by joshmoore** [comment]
See http://downloads.openmicroscopy.org/omero/5.0.2-rc1/#py -- new logos would be necessary. /cc @gusferguson

**Comment by hflynn** [comment]
I wonder if this would be better placed underneath the virtual appliance and above the API docs? Also 'download the Python…' reads strangely - 'Python bundle'? It really needs another word in there.

**Comment by joshmoore** [comment]
@hflynn : regarding positioning, happy with whatever. Also happy to turn over to anyone else who wants to fiddle.

**Comment by hflynn** [comment]
Is that a request for me to finish sorting this out for you? ;)

**Comment by joshmoore** [comment]
That's a "I'm not going to get myself into a bike-shedding PR at the moment" :smile:

**Comment by joshmoore** [comment]
Icons & py-section move pushed. (Tried _after_ api)

**Comment by hflynn** [comment]
Downloads page regenerated - looks fine to me. Good to merge unless anyone CC'ed has any comments.

**Comment by manics** [comment]
Some section titles contain `5.0.2-rc1`, some don't.

**Comment by hflynn** [comment]
Ah, it is the two updated sections that contain the version number. I can remove it from the server section on #106 if you remove it on this one @joshmoore ? We don't really need the version number in the subsections.

**Comment by joshmoore** [comment]
Done.

**Comment by hflynn** [comment]
:+1:

**Comment by joshmoore** [comment]
--rebased-to #107

**Pull request merged**
