### PR TITLE
Adding Demo server & VA text to OMERO downloads page

### PR DESCRIPTION
**Pull request by hflynn**
Graeme Ball suggested we add some directions for people reaching the downloads page who don't have an institutional server and explain what the VA is for those who come here without reading the documentation.
cc @pwalczysko

### CODE REVIEW

**Comment by hflynn** [comment]
see http://ci.openmicroscopy.org/job/OMERO-5.0-release-downloads/lastSuccessfulBuild/artifact/content/index.html

**Comment by mtbc** [comment]
Good to merge. +1 for no "here" links!

**Comment by sbesson** [comment]
@hflynn: can you rebase this on top of develop?

**Comment by hflynn** [comment]
--rebased-to #54

**Comment by hflynn** [comment]
@sbesson done.

**Pull request merged**
